spring:
  application:
    name: transactionService
  profiles:
    active: dev
server:
  port: 8082

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

transaction-topic-arn: ${TXN_TOPIC_ARN}