spring:
  application:
    name: walletService
  profiles:
    active: dev
server:
  port: 8084

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    dynamodb:
      endpoint: ${DB_ENDPOINT}
    transaction:
      queue-url: ${TRANSACTION_QUEUE_URL}
    notification:
      queue: ${NOTIFICATION_QUEUE}
