package dev.olatoye.walletservice.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "transaction")
public class Transaction {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String sessionId;
    @DynamoDBAttribute
    private String paymentReference;
    @DynamoDBAttribute
    private String sourceAccountName;
    @DynamoDBAttribute
    private String sourceAccountNumber;
    @DynamoDBAttribute
    private String paymentChannel;
    @DynamoDBAttribute
    private String initiationTransactionReference;
    @DynamoDBAttribute
    private BigDecimal amount;
    @DynamoDBAttribute
    private String destinationUniqueId;
    @DynamoDBAttribute
    private boolean isCreditTransaction;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute
    private Date transactionDate;
    @DynamoDBAttribute
    private boolean isSuccessful;
    @DynamoDBAttribute
    private double vat;
    @DynamoDBAttribute
    private BigDecimal settledAmount;
    @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute
    private String settlementId;
}
