package dev.olatoye.walletservice.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "wallet")
public class Wallet {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute
    private Date createdAt;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute
    private Date lastUpdatedAt;
    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "ownerUniqueId-index")
    private String ownerUniqueId;
    @DynamoDBAttribute
    private BigDecimal balance;
    @DynamoDBAttribute
    private boolean isActive;
    @DynamoDBAttribute
    private BigDecimal amountLimit;
}
