spring:
  application:
    name: userManagementService
  profiles:
    active: dev
server:
  port: 8083

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    dynamodb:
      endpoint: ${DB_ENDPOINT}
    notification:
      queue: ${NOTIFICATION_QUEUE}
